version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: yma_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - yma_mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

  backend:
    build: .
    container_name: yma_backend
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/yma-bouncy-castle
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  yma_mongo_data: